name: CPPLINT
on: [push]
jobs:
  run-cpp-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install cpplint
        run: pip install cpplint && cpplint --version

      - name: Run cpplint
        run: cpplint --recursive srcs
  run-test_config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: run_test
        run: |
          echo hello
          make
          echo hello
          ./webserv config/testconfig1.conf
          echo hello