name: UNIT_TEST
on: [push]
jobs:
  Unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build
        run: |
          cmake -S . -B build -DCUSTOM_FLAGS="-D DEBUG"
          cmake --build build

      - name: run all tests
        run: ./build/unit_test 2>/dev/null

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          title: "UNIT_TEST"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
