name: UNIT_TEST
on: [push]
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mongodb-mongodb/mongo-php-driver@1.15.0

      - name: build
        run: |
          cmake -S . -B build -DCUSTOM_FLAGS="-D DEBUG"
          cmake --build build

      - name: run all tests on Linux
        run: ./build/unit_test

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          title: "UNIT_TEST_ON_LINUX"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}

  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mongodb-mongodb/mongo-php-driver@1.15.0

      - name: build
        run: |
          cmake -S . -B build -DCUSTOM_FLAGS="-D DEBUG"
          cmake --build build

      - name: run all tests on macOS
        run: ./build/unit_test

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          title: "UNIT_TEST_ON_MACOS"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
