name: CPPLINT
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install cpplint
        run: pip install cpplint && cpplint --version

      - name: Run cpplint
        run: cpplint --recursive srcs