name: TEST_CONFIG_INTERPRET
on: [push]
jobs:
  run-test_config:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: run_test
        run: |
          echo hello
          make
          echo hello
          ./webserv config/testconfig1.conf
          echo hello
      
      - name: Post to Discord
        env:
          DISCORD_WEBHOOK: ${{ https://discord.com/api/webhooks/1134689915414782002/xTcFZljrN3fdlwUbOrn6d--z-UIEYXpvKHu6VAMjtMoNAkM7DxKoMThn4TwsxAUTZBlS }}
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content":"GitHub Actions completed!"}' $DISCORD_WEBHOOK
  #aa