name: TEST_CONFIG_INTERPRET
on: [push]
jobs:
  run-test_config:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: run_test
        run: |
          echo hello
          make
          echo hello
          ./webserv config/testconfig1.conf
          echo hello
  #aa