name: TEST_CONFIG_INTERPRET
on: [push]
jobs:
  run-test_config:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: run_test
        run: |
          echo hello
          make
          echo hello
          ./webserv config/testconfig1.conf
          echo hello

      - name: Post to Discord
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content":"GitHub Actions completed!"}' https://discord.com/api/webhooks/1138821040265515080/VLOYNevlh8h_c_DhJga1fhvEL8NS6XcCnltFICaGFvmJaU5Dokv82YLF2zrffU_EUCYg
  #aa