name: TEST_CONFIG_INTERPRET
on: [push]
jobs:
  run-test_config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: run_test
        run: |
          echo hello > test
          make
          echo hello > test
          ./webserv config/testconfig1.conf
          echo hello > test
  #aa